controllers:
    resource: ../src/Controller/
    type: attribute

auth.login:
    path: /login
    controller: App\Login
    methods: [GET]

auth.logout:
    path: /logout
    methods: [GET]

auth.connect.google:
    path: /connect/google
    methods: [GET]
