version: "2.7"

server: 
    command: php /srv/app/public/index.php
    env:
        - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
    address: 0.0.0.0:8080
    fcgi:
        address: 0.0.0.0:9000
    pool:
        num_workers: 4
        max_jobs: 2
        allocate_timeout: 60s
        destroy_timeout: 60s
    middleware: [ "static", "gzip" ]
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]
        
logs:
    mode: production
    channels:
        http:
            level: info 
        server:
            level: info
            mode: raw
        metrics:
            level: info 

status:
    address: 0.0.0.0:2114
